project/luckyanimals/config/routes.rb
Rails.application.routes.draw do

  resources :posts

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  
  get 'animals/:id/delete', to: 'animals#destroy', as: 'delete_animal'
  get 'animals/my', to: 'animals#my_animals', as: 'my_animals'

  resources :animals do 
    member do
      get 'adopt'
    end
  end

  root 'sessions#new'

end

project/luckyanimals/app/models/animal.rb
class Animal < ActiveRecord::Base
	belongs_to :user
	has_many :posts
	has_many :post_attachments, through: :posts

	validates :name, presence: true
	validates :gender, presence: true
	validates :birthday, presence: true
	validates :species, presence: true
	validates :size, presence: true
	validates :coat_color, presence: true
	validates :eyes_color, presence: true
	validates :neutered, presence: true

	validates :posts, presence:true
	
	belongs_to :user
	has_many :posts, :dependent => :destroy

	accepts_nested_attributes_for :posts, :allow_destroy => true

	def birthday=(date)
     begin
       parsed = Date.strptime(date,'%m/%d/%Y')
       super parsed
     rescue
       date         
     end
  end

end

project/luckyanimals/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :animal
	has_many :post_attachments, :dependent => :destroy
    
    accepts_nested_attributes_for :post_attachments, :allow_destroy => true
end

project/luckyanimals/app/models/post_attachment.rb
class PostAttachment < ActiveRecord::Base
   mount_uploader :image, ImageUploader
   belongs_to :post
end

project/luckyanimals/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  # attr_accessible :email, :password, :password_confirmation

  validates_uniqueness_of :email
end

project/luckyanimals/app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show , :adopt, :destroy]

  def index
    @animals = Animal.where("user_id != ?" , @current_user).where(adopted: false)
    render "index"
  end

  def my_animals
    @animals = Animal.where(user: @current_user)

    render "my_animals"
  end

  def new
    @animal = Animal.new
  end

  def show
  end

  def adopt
    @animal.adopted = true
    @animal.user = @current_user
    if @animal.save
      
      redirect_to animal_url, notice: @animal.name + " was adopted. The world is getting better because of you. :)"
    
    else
      redirect_to animal_url, alert: @animal.name + " coud not be adopted."
    end
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.adopted = false
    @animal.user = @current_user
    

    unless  params[:post_attachments].blank?
      #  "Please add a picture for your pet."
      @animal.posts = Array.new 
      post = Post.new
      post.description = "New animal added for adoption."
      
      post.post_attachments = Array.new

      params[:post_attachments]['image'].each do |a|
        attachment = PostAttachment.new
        attachment.image = a
        post.post_attachments.push attachment
      end

      @animal.posts.push post
      
    end

    if @animal.save
      redirect_to my_animals_url, notice: "New animal added for adoption!"
    else
      render "new"
    end
    
  end

  def destroy
    @animal.destroy
    redirect_to animals_url, notice: @animal.name + " was deleted."
  end

  def animal_params

    params.require(:animal)
          .permit(:name, :birthday, :gender, :species, :size, :coat_color, :eyes_color, :neutered, :adopted, :post_attachments)
            
  end

  def set_animal
    @animal = Animal.find(params[:id])
  end

end

project/luckyanimals/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authorize

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    puts params.inspect
    if (params[:controller] != "sessions")
      #%w  - atalho para criar array
      puts params.inspect
      if !(params[:controller] == "users" && %w[new create].include?( params[:action]))
        redirect_to login_url, alert: "Not authorized" if current_user.nil?
      end
    end
  end
end

project/luckyanimals/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:description)
    end
end

project/luckyanimals/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to animals_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

project/luckyanimals/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation)
  end
end

project/luckyanimals/app/helpers/animals_helper.rb
module AnimalsHelper
end

project/luckyanimals/app/helpers/application_helper.rb
module ApplicationHelper
end

project/luckyanimals/app/helpers/posts_helper.rb
module PostsHelper
end

project/luckyanimals/app/helpers/sessions_helper.rb
module SessionsHelper
end

project/luckyanimals/app/helpers/users_helper.rb
module UsersHelper
end

project/luckyanimals/app/views/animals/_grid.html.erb
<div class="row">
		<% @animals.each do |animal| %>
  			<div class="col-sm-6 col-md-4">
    			<div class="thumbnail">
    				<% if animal.posts.first %>
      					<%= image_tag animal.posts.first.post_attachments.first.image_url%>
      				<%end%>
      				<div class="caption">
	        			<h3><%=animal.name %></h3>
	        			<p>
	        				is a 
    							<% case animal.gender %> 
          						<% when 1 %>
            						<%="female " %>
          						<% when 2 %>
            						<%= "male " %>
            					<% else %>
          							<%="..."%>
          						<% end %>
          					 <% case animal.neutered%>
          						<% when true %>
            						<%="neutered" %>
          						<% when false %>
            						<%= "" %>
          						<% else %>
          						<%="..."%>
    						<% end %>

          					 born at <%= animal.birthday.strftime("%e %B %Y") %>. 
	        			</p>
	        			<p>
	        				
	        				<a href=<%= animal_path animal.id%> class="btn btn-default" role="button">Details</a>
	        			</p>
       				</div>
    			</div>
  			</div>
		<%end%>
	</div>

project/luckyanimals/app/views/animals/index.html.erb
<div class="container"> 
	<div class="page-header">
		<h1>Look for adoption</h1>
	</div>

	<%= render "grid" %>
</div>

project/luckyanimals/app/views/animals/my_animals.erb
<div class="container"> 
	<div class="page-header">
		<h1>My animals</h1>
	</div>

	<%= render "grid" %>
</div>

project/luckyanimals/app/views/animals/new.html.erb
<div class="container"> 

<div class="page-header">
  <h1>New animal</h1>
</div>

<%= form_for @animal, :html => {class: "form-horizontal"}  do |f| %>
  

  

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-8">
      <%= f.text_field :name , class: "form-control", placeholder: "name"%>
      </div>
  </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label"> Birthday </label>
      <div class="col-sm-8">
        <div class='input-group date' id='datetimepicker1'>
          <%= f.text_field :birthday,  class: "form-control", placeholder: "birthday" %>
          <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
          </span>
        </div>
      </div>
    </div>
<script type="text/javascript">
  
  $(function () {
    $('#datetimepicker1').datetimepicker({ format: 'MM/DD/YYYY' });
   });

  $(":file").filestyle();

</script>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label"> Gender </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :gender, '1' %> Female <br/>
      </label>
    <label class="checkbox-inline">
      <%= f.radio_button :gender, '2' %> Male <br/>
      </label>

  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label"> Species </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :species, '1' %> Dog <br />
    </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :species, '2' %> Cat <br />
    </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :species, '3' %> Other <br />
    </label>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label"> Size </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :size, '1' %> Small <br />
    </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :size, '2' %> Medium <br />
    </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :size, '3' %> Big <br />
    </label>
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label"> Coat color </label>
    <div class="col-sm-8">
      <%= f.text_field :coat_color , class: "form-control", placeholder: "coat color"%>
      </div>
    
  </div>
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label"> Eyes color</label>
    <div class="col-sm-8">
      <%= f.text_field :eyes_color , class: "form-control", placeholder: "eyes color"%>
      </div>
    
  </div>
  
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label"> Neutered </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :neutered, 'true' %> Yes <br/>
    </label>
    <label class="checkbox-inline"> 
      <%= f.radio_button :neutered, 'false' %> No <br/>
    </label>
  </div>

  <%= f.fields_for :post_attachments do |p| %>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label"> Image </label>
      <div class="col-sm-8">
        <%= p.file_field :image, :multiple => true, name: "post_attachments[image][]", class: "filestyle" %>
      </div>
    </div>

  <% end %>


  <div class="actions form-group col-sm-3 control-label"><%= f.submit "Create" , class: "btn btn-primary btn-lg"%></div>
  </br>
  </br>
  </br>
  </br>

  <% if @animal.errors.any? %>
    <div class="alert alert-danger"> 
      <strong> Form is invalid. </strong>
      <ul class="list-inline">
        <% @animal.errors.full_messages.each do |message| %>
          <li> <%= message %>. </li>
        <% end %>
      </ul>
    </div>
  <% end %>

<% end %>
</div>

project/luckyanimals/app/views/animals/show.html.erb
  
<div class="container"> 
  <div class="page-header">
    <div style="float: right;">
        <% if @animal.adopted %>
          <button type="button" class="btn btn-lg btn-success">Adopted</button>
        <% end %>
        <% if @animal.user != current_user %>
          <a href=<%= adopt_animal_path @animal.id%> class="btn btn-lg btn-warning" role="button" confirm="Do you really wanna adopt this animal?">Adopt</a>
        <% end %>
        
    </div>
    <div> 
      <h1> <%= @animal.name %> </h1>
     </div>
      
  </div>
  <p>  
    <strong> Birthday: </strong>
    <%= @animal.birthday.strftime("%Y/%m/%d") %>
  </p>
  <p>
    <strong> Gender: </strong>
    <% case @animal.gender %> 
          <% when 1 %>
            <%="Female" %>
          <% when 2 %>
            <%= "Male" %>
            <% else %>
          <%="..."%>
          <% end %>
  </p>
  <p>
    <strong> Species: </strong>
    <% case @animal.species %>
          <% when 1 %>
            <%="Dog" %>
          <% when 2 %>
            <%= "Cat" %>
          <% when 3 %>
            <%= "Other" %>
          <% else %>
            <%="..."%>
          <% end %>
  </p>
  <p>
    <strong> Size: </strong>
    <% case @animal.size%>
          <% when 1 %>
            <%="Small" %>
          <% when 2 %>
            <%= "Medium" %>
          <% when 3 %>
            <%= "Big" %>
            <% else %>
          <%="..."%>
          <% end %>
    
  </p>
  <p>
    <strong> Coat Color: </strong>
    <%= @animal.coat_color %>
  </p>
  <p>
    <strong> Eyes Color: </strong>
    <%= @animal.eyes_color %>
  </p>
  
  <p>
    <strong> Neutered: </strong>
    <% case @animal.neutered%>
          <% when true %>
            <%="Yes" %>
          <% when false %>
            <%= "No" %>
          <% else %>
          <%="..."%>
    <% end %>
    
  </p>
  
  <p>
  
  <% if @animal.posts.first %>  
    <% @animal.posts.first.post_attachments.each do |p| %>
         <%= image_tag p.image_url(:thumb), :class => "img-rounded" if p.image? %>
    <% end %>
  <%end %>
  </p>
 <p> 
  <!--<button type="button" class="btn btn-lg btn-link"><%= link_to 'Edit', edit_animal_path(@animal) %> </button>-->
  
    <%= link_to 'Remove', delete_animal_path , :confirm =>  'Are you sure you want to remove this animal? This cannot be undone.', :class=>"btn btn-default" %> 
  
  
  <button type="button" class="btn btn-default"><%= link_to 'Back', animals_path %> </button>

</p>

</div>

project/luckyanimals/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
<head>
  <title>Luckyanimals</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 
      
</head>
<body role="document">


    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href=<%=root_path%>>Lucky Animals</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href=<%=root_path%>>Home</a></li>
            <li><a href=<%=root_path + "/#about" %>>About</a></li>
            <li><a href=<%= animals_path%>>Look for adoption</a></li>
            <li><a href=<%= my_animals_path%>>My animals</a></li>
            <li><a href=<%= new_animal_path%>>New Animal</a></li>
            <!--<li class="dropdown">
              <a  class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Animals <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href=<%= animals_path%>>List</a></li>
                <li><a href= <%= new_animal_path%>>New</a></li>
                <li><a href="http://getbootstrap.com/examples/theme/#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="http://getbootstrap.com/examples/theme/#">Separated link</a></li>
                <li><a href="http://getbootstrap.com/examples/theme/#">One more separated link</a></li>
              </ul>
            </li>-->  
            
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% if current_user %>

                <li class="active"><a href="./">Logged in as <%= current_user.email %>.  <span class="sr-only">(current)</span></a></li>
                <li><a href=<%=logout_path %>> Log Out</a></li>
              <% else %>
                <li><a href=<%=signup_path %>>Sign Up</a></li> 
                <li><a href=<%=login_path %>>Log In</a></li>
              <% end %>
              
            </li>
            </ul>
         
        </div><!--/.nav-collapse -->

        
      </div>
    </nav>

  
    <div class="container theme-showcase" role="main">
      <% if notice %>
        <div class="alert alert-success" role="alert"> 
          <%= notice%> 
        </div>
      <% end %>
    </div>
    </br>
    </br>
      <%= yield %>
      </br>
      
<div class="container theme-showcase" role="main">
      <% if flash.alert %>
        <div class="alert alert-danger" role="alert">
    	     <%=  flash.alert%>
        </div>
      <% end %>
    </div>

  </div>
</body>
</html>

project/luckyanimals/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

project/luckyanimals/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

project/luckyanimals/app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

project/luckyanimals/app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

project/luckyanimals/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

project/luckyanimals/app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign Up</h1>
</div>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>